export default {
  products: [
    {
      _id: '1',
      name: "Узкая рубашка",
      category: 'Shirts',
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
    },
    {
      _id: '2',
      name: "Приталенная рубашка",
      category: 'Shirts',
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '3',
      name: "Свободные шорты",
      category: 'Pants',
      image: "/images/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 3.5,
      numReviews: 8,
    },
    {
        _id: '4',
        name: "Брюки",
        category: 'Pants',
        image: "/images/d1.jpg",
        price: 100,
        brand: "Nike",
        rating: 5,
        numReviews: 20,
      },
  ],
};
